name: Run Tests

on:
  workflow_dispatch:

jobs:
  my_job:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          # The Java version to set up. Takes a whole or semver Java version. See examples of supported syntax in README file
          java-version: 17
          # The path to the `.java-version` file. See examples of supported syntax in README file
          distribution: corretto

      - name: Setup Maven
      # You may pin to the exact commit or the version.
      # uses: stCarolas/setup-maven@d6af6abeda15e98926a57b5aa970a96bb37f97d1
        uses: stCarolas/setup-maven@v5
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0
          maven-version: 3.9.5 # optional, default is 3.8.2

      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Run Tests
        run: mvn test

      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4

      - name: Generate maven wrapper
        run: mvn -N io.takari:maven:wrapper
        
      #- uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          



